version: 2.1

orbs:
  rust: circleci/rust@1.6.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.86
    steps:
      - checkout
      - rust/clippy:
          flags: --all-targets
      - rust/test

workflows:
  test:
    jobs:
      - test
